### ISSUE TITLE
Acabar Web

### ISSUE THREAD

**Issue by pausp1** [HiddenLair/Run4YourLife#146]

**Comment by PereViader** [comment]
You could upload the web directly to github and work from there.
In order to do this you need to switch from "Develop" branch to "gh-pages". When you do this, all the contents from the project will disappear because they are unconnected branches.

Github provides static websites: https://hiddenlair.github.io/Run4YourLife/

Delete the index.md and place the index.html file of the website you are building

**Comment by PereViader** [comment]
We will have to add link the download button to a file.

The accepted answer should be the way to go.
https://stackoverflow.com/questions/24987542/is-there-a-link-to-github-for-downloading-a-file-in-the-latest-release-of-a-repo
