### ISSUE TITLE
Crosshair

### ISSUE THREAD

**Issue by Aenerida** [HiddenLair/Run4YourLife#327]
I need the size of the crosshair (pixel x pixel) and the assigment of every skill with his buttom (ex; Y-Fire /B-Wind/etc)

**Comment by Moaif** [comment]
About the corsshair size, i dont know if we can do it with pixel reference, because we are supporting multiple resolutions, and ppp from diferent pc's.(I dont know much about this subject)

But for the skills i think we may have 2 options:
- First one:
X: Wind
Y:Thunder
B:Bomb
A:EarthPike
This one leaves the thunder up, and the pike down, where they are spawned in the game, however the wind, is setted in the opposite direction from which it comes. This option has the advantage of color-relation between buttons and skills, blue for wind, yellow for thunder, red for bomb, and green for earth.

-Second one:
X:Bomb
Y:Thunder
B:Wind
A:Earthpike
On this one, we set the skill position depending on where they spawn in the game, despite the bobm dont spawn from any position, this one is placed on the last button available.

**Comment by PereViader** [comment]
I don't think we will have problems with diferent ppp.

Make it really big and we will then downsample it.

I believe downsampling problems only appear when working with really small UI elements which the crosshair isn't.

**Comment by PereViader** [comment]
About the button placement I like the second one Moaif proposed
