### ISSUE TITLE
Fix runner animation controller

### ISSUE THREAD

**Issue by PereViader** [HiddenLair/Run4YourLife#511]
Runner Animator Controller does not work perfectly while double jumping.

For some reason, when double jumping and landing prematurely, if the player jumps again then the runner plays the double jump animation instead of the run animation.

**Comment by Moaif** [comment]
This is cause we have a transition from "Run" to "Double Jump" if the player press jump button while the runner "is ground" is false, this sometimes happends when he is just running, cause of the controller. This transition was made to solve the problem where you fall from somewhere, and if jumping, the runner would made a normal jump, but could not make a second one, meaning that the jump should be the second one, as we had it before, from running you could only pass to air on pressing jump, becoming imposible to reach double jump animation in this case.

Posibles solutions:
-Make air transition automatically when not grounded(will have some artifacts due to the controller behaviour), and errase transition from "Run" to "Double jump"

-Make an air timer to check that we are really in air, in order to check it in the transition from "Run" to "Double jump"

-Make the transition check the "y" speed, if it pass a certain thresshold, we make the transition.
