### ISSUE TITLE
Make destruction particle for destructible wall

### ISSUE THREAD

**Issue by PereViader** [HiddenLair/Run4YourLife#568]

**Comment by pausp1** [comment]
This is how I left it:
![image](https://user-images.githubusercontent.com/32684237/43834760-941ec49e-9b0f-11e8-8df3-4b5f026f73d9.png)

I've changed the dust totally and I've changed the material of the rocks (I kept the text because I like It) and some particle parammeters, We'll talk about this on the meeting today
