### ISSUE TITLE
Phase 2 Hand problems

### ISSUE THREAD

**Issue by Moaif** [HiddenLair/Run4YourLife#614]
We found 2 problems on the hand.

First one, the boss use this skill, and then the phase just ends, we change camera, and right then, the hand appears on the right part of the screen.

And second, the hand appeared from the left, but with more than half its normal speed slow.

**Comment by PereViader** [comment]
The bug works as follows.

While the boss is executing the ending transition, it's controls are not disabled.

This means that while it is transitioning, you can execute a melee. The animation won't be seed because the timeline is overriding the animation but the coroutines are still called and executed.
